version: '3'

services:
  scloudnode0:
    container_name: scloudnode0
    image: "tendermint/scloudnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-scloud.log}
    volumes:
      - ./build:/scloud:Z
    networks:
      localnet:
        ipv4_address: 10.10.10.2

  scloudnode1:
    container_name: scloudnode1
    image: "tendermint/scloudnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-scloud.log}
    volumes:
      - ./build:/scloud:Z
    networks:
      localnet:
        ipv4_address: 10.10.10.3

  scloudnode2:
    container_name: scloudnode2
    image: "tendermint/scloudnode"
    environment:
      - ID=2
      - LOG=${LOG:-scloud.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/scloud:Z
    networks:
      localnet:
        ipv4_address: 10.10.10.4

  scloudnode3:
    container_name: scloudnode3
    image: "tendermint/scloudnode"
    environment:
      - ID=3
      - LOG=${LOG:-scloud.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/scloud:Z
    networks:
      localnet:
        ipv4_address: 10.10.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 10.10.10.0/16

